<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAQQ0Nt6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAQQ0Nt6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAQQ0Nt6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAQQ0Nt6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAQQ0Nt6\App_KernelDevDebugContainer([
    'container.build_hash' => 'AQQ0Nt6',
    'container.build_id' => 'd634231b',
    'container.build_time' => 1711103107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAQQ0Nt6');
