<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhXOznN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhXOznN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPhXOznN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPhXOznN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPhXOznN\App_KernelDevDebugContainer([
    'container.build_hash' => 'PhXOznN',
    'container.build_id' => '779c41be',
    'container.build_time' => 1713783438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhXOznN');
